server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dangxia?useSSL=false
#    url: jdbc:mysql://140.143.225.154:3306/dangxia?useSSL=false&characterEncoding=utf8
    username: root
    password: Mysqlkxrjsw37
  redis:
#    host: 172.0.0.1
    host: localhost
    port: 6379
    database: 0
  cloud:
      consul:
        host: 127.0.0.2
        port: 8500
        discovery:
          enabled: true
          service-name: ${server.application.name}
          health-check-interval: 10s
          register: true
          tags: foo=bar, baz
          health-check-path: /health
          instance-id: consul-miya
#    static-locations: classpath:/testStatic/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/webapp
#    host: 140.143.225.154
mqtt:
  id: -3
